services:
  - type: web
    name: panchratna
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: "composer install"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sql12791025
      - key: DB_USERNAME
        value: sql12791025
      - key: DB_PASSWORD
        value: ZKmz4ZuNtw
