services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: <paste output of `php artisan key:generate --show`>
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sql12791025
      - key: DB_USERNAME
        value: sql12791025
      - key: DB_PASSWORD
        value: ZKmz4ZuNtw
